import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IChiTietSanPhamTiepNhan } from '../chi-tiet-san-pham-tiep-nhan.model';
import { ChiTietSanPhamTiepNhanService } from '../service/chi-tiet-san-pham-tiep-nhan.service';
import { ChiTietSanPhamTiepNhanDeleteDialogComponent } from '../delete/chi-tiet-san-pham-tiep-nhan-delete-dialog.component';

@Component({
  selector: 'jhi-chi-tiet-san-pham-tiep-nhan',
  templateUrl: './chi-tiet-san-pham-tiep-nhan.component.html',
})
export class ChiTietSanPhamTiepNhanComponent implements OnInit {
  chiTietSanPhamTiepNhans?: IChiTietSanPhamTiepNhan[];
  isLoading = false;
  columnDefinitions: Column[] = [];
  gridOptions: GridOption = {};
  chiTietSanPhamTiepNhan: any[] = [];

  constructor(protected chiTietSanPhamTiepNhanService: ChiTietSanPhamTiepNhanService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.chiTietSanPhamTiepNhanService.query().subscribe({
      next: (res: HttpResponse<IChiTietSanPhamTiepNhan[]>) => {
        this.isLoading = false;
        this.chiTietSanPhamTiepNhans = res.body ?? [];
      },
      error: () => {
        this.isLoading = false;
      },
    });
  }

  ngOnInit(): void {
    this.loadAll();
    this.columnDefinitions = [
      {
        id: 'id',
        field: 'id',
        name: 'STT',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'maTiepNhan',
        field: 'maTiepNhan',
        name: 'Mã tiếp nhận',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'maNam',
        field: 'maNam',
        name: 'Mã năm',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'ngayTaoDon',
        field: 'ngayTaoDon',
        name: 'Ngày tạo đơn',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'ngayTiepNhan',
        field: 'ngayTiepNhan',
        name: 'Ngày tiếp nhận',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'ngayPhanTich',
        field: 'ngayPhanTich',
        name: 'Ngày phân tích',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'tenNhanVien',
        field: 'tenNhanVien',
        name: 'Tên nhân viên',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'tenKhachHang',
        field: 'tenKhachHang',
        name: 'Tên Khách hàng',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'nhomKhachHang',
        field: 'nhomKhachHang',
        name: 'Nhóm khách hàng',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'tinhThanh',
        field: 'tinhThanh',
        name: 'Tỉnh thành',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'tenSanPham',
        field: 'tenSanPham',
        name: 'Tên sản phẩm',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      }, {
        id: 'nganh',
        field: 'nganh',
        name: 'Ngành',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'chungLoai',
        field: 'chungLoai',
        name: 'Chủng loại',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'nhomSanPham',
        field: 'nhomSanPham',
        name: 'Nhóm sản phẩm',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'soLuongKhachGiao',
        field: 'soLuongKhachGiao',
        name: 'Số lượng khách giao',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'soLuongThucNhan',
        field: 'soLuongThucNhan',
        name: 'Số lượng thực nhận',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'soLuongDoiMoi',
        field: 'soLuongDoiMoi',
        name: 'Số lượng đổi mới',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'loiKT',
        field: 'loiKT',
        name: 'Lỗi kĩ thuật',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'loiLinhDong',
        field: 'loiLinhDong',
        name: 'Lỗi linh động',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Cầu diode Silijino',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Tụ hoá L.H',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Tụ hoá Aishi',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Tụ film cctc',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Tụ film Hulysol',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Transistor',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Điện trở',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Chặn (Biến áp)',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Cuộn lọc',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Hỏng IC vcc',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Hỏng IC fes',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Lỗi nguồn',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Chập mạch',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Bong mạch',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Công tắc',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Long keo',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Đômino, rắc cắm',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Dây nối LED',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Mất lò xo, tai cài',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Dây DC',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Dây AC',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Bong, nứt mối hàn',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Pin, tiếp xúc lò xo',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Tiếp xúc cọc tiếp điện, đầu đèn',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Hỏng LED',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Nứt vỡ nhựa, cover',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Móp, nứt vỡ đui',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Gãy cổ + cơ khớp, tai cài',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Nước vào',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Điện áp cao',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Cháy nổ nguồn',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Cũ, ẩm mốc, ố rỉ',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Om nhiệt',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Vỡ ống, kính',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Lỗi khác',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
      {
        id: 'lois',
        field: 'lois',
        name: 'Sáng bình thường',
        excludeFromColumnPicker: true,
        excludeFromGridMenu: true,
        excludeFromHeaderMenu: true,
        maxWidth: 60,
        minWidth: 60,
      },
    ];
    this.gridOptions = {
      enableAutoResize: true,
      enableSorting: true,
      enableFiltering: true,
      enablePagination: true,
      pagination: {
        pageSizes: [30, 50, 100],
        pageSize: this.chiTietSanPhamTiepNhan.length,
      },
      editable: true,
      enableCellNavigation: true,
      gridHeight: 620,
      gridWidth: 1750,
    }
  }

  trackId(_index: number, item: IChiTietSanPhamTiepNhan): number {
    return item.id!;
  }

  delete(chiTietSanPhamTiepNhan: IChiTietSanPhamTiepNhan): void {
    const modalRef = this.modalService.open(ChiTietSanPhamTiepNhanDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.chiTietSanPhamTiepNhan = chiTietSanPhamTiepNhan;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}
